export type IconName =
  | 'calendar'
  | 'chevron-down'
  | 'chevron-left'
  | 'chevron-right'
  | 'close'
  | 'elements'
  | 'heart'
  | 'home'
  | 'horizontal-tree-lines'
  | 'mountains'
  | 'price'
  | 'print'
  | 'triangle'
  | 'users'
  | 'world'
  | 'filter'
  | 'info';
